---
abstract: 'Determine Swiss holidays'
author:
  - 'Michael Herrmann <michael@herrmann.io>'
build_requires:
  Date::Calc: 5.0
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Holidays-CH
provides:
  Date::Holidays::CH:
    file: lib/Date/Holidays/CH.pm
    version: v0.1.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Date-Holidays-CH
  homepage: http://github.com/rainboxx/Date-Holidays-CH/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rainboxx/Date-Holidays-CH.git
version: v0.1.3
